Initial release with get_url functionality
antmicro/symbiflow-tools-package-manager pull request #1
Opened 2020-10-13 14:32 UTC by kowalewskijan

This is an internal PR to review the initial release before we create a PR to mainline.

2020-10-13 14:55 UTC, acomodi requested changes
Some comments in.

In general looks good, I think there are some things missing that could be worth adding:

- Python auto-formatter (to test in CI)
- Addition of a console entry point in the setup, such that we can call this functionality from command line.

2020-10-13 14:55 UTC, acomodi commented on setup.py
> +      author_email='jkowalewski@antmicro.com',
I would change this to symbiflow authors probably

```suggestion
      author='SymbiFlow Authors',
      author_email='symbiflow@lists.librecores.org',
```

2020-10-13 14:55 UTC, acomodi commented on stpm/__init__.py
> +import json, requests
IMO it is better to separate each import in its own line

2020-10-13 14:55 UTC, acomodi commented on stpm/__init__.py
> +# Copyright (C) 2020  The SymbiFlow Authors.
Python scripts should have the utf-encoding and python shebang as well. (I think this is not getting tested by the CI scripts?).

e.g. :
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright ...
```

2020-10-13 14:55 UTC, acomodi commented on stpm/__init__.py
> +def get_url(project='symbiflow-arch-defs', build_name='install'):
Probably we need to rename this to something like `get_latest_artifact_url`.

2020-10-13 14:56 UTC, acomodi commented
I think that ones the comments are fixed we can then proceed by closing this PR and opening one directly upstream.

2020-10-14 17:36 UTC, kowalewskijan commented
I resolved the comments. Closing here, I'll open the PR in mainline repository.

2020-10-14 17:36 UTC, closed without merging